programma : ghost.o cont_sett_struct.o
	gcc ghost.o cont_sett_struct.o -lxdo -o ghost

ghost.o : ghost.c
	gcc -c ghost.c -lxdo

cont_sett_struct.o :cont_sett_struct.c
	gcc -lxdo -c cont_sett_struct.c


